# fly.toml app configuration file generated for twilio-cable on 2024-12-02T17:20:58-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'twilio-cable'
primary_region = 'sea'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = './Dockerfile'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
