default: &default
  # Phone number to make calls from or to
  # phone_number: "+123456789"

development:
  <<: *default

production:
  <<: *default
  phone_number: "+18775357613"
  status_callback: https://twilio-ai-demo.fly.dev/twilio/status
  stream_callback: wss://twilio-cable.fly.dev/twilio
